### ISSUE TITLE
 MDNS broadcasting via Python

### ISSUE THREAD

**Issue by jtc42** [labthings/python-labthings#12]
OpenFlexure Microscope uses OS-level zeroconf for broadcasting. We should have LabThings automatically add zeroconf records identifying the server as a Lab Thing.

Python zeroconf library?

**Comment by ChasNelson1990** [comment]
Not sure if 'Python zeroconf library?' is a question about whether there is one or whether to use it. But either way, probably good to link to it here for the future: https://python-zeroconf.readthedocs.io/en/latest/index.html

**Comment by jtc42** [comment]
I should really mark this as "in progress" somehow. Been playing with python-zeroconf this week and seems to generally work fairly well.

**Comment by jtc42** [comment]
Closed by df2bc7132dec42906810242925235acb83207486
