### ISSUE TITLE
Web socket interface

### ISSUE THREAD

**Issue by jtc42** [labthings/python-labthings#17]
This is absolutely critical for the entire event-driven side of things.

Base on Mozilla web thing events. Should be easy enough to handle subscriptions etc

## Event types

* Debug
* Info
* Warning
* Error
* Data (experimental)
* Tasks (progress, in-progress data, etc)

**Comment by ChasNelson1990** [comment]
I am a massive fan of loguru: https://github.com/Delgan/loguru

And there is a guide for sending logs over networks: https://loguru.readthedocs.io/en/stable/resources/recipes.html#sending-and-receiving-log-messages-across-network-or-processes

**Comment by jtc42** [comment]
Thanks for the link. All the websocket messages will be formatted as described by the Mozilla Web Thing framework, so something like that but with a (very) custom formatting could work?

I have the backend code for handling event messages over websocket in place now, so hooking into that will be easy enough.

**Comment by jtc42** [comment]
Closing as all solutions for Flask are hacky. For a modern, async server implementation with websocket support, see https://github.com/labthings/python-thingserver
