### ISSUE TITLE
Schema validation errors get eaten by ActionViews

### ISSUE THREAD

**Issue by rwb27** [labthings/python-labthings#184]
**Describe the bug**
If an Action is called with invalid data (i.e. data that doesn't match the schema), no error is raised immediately.  Instead, we get an HTTP 201 response, and the exception is buried in the JSON log/output value.

**To Reproduce**
Create an ActionView with an ``args`` schema including a validation constraint, and clall it with invalid JSON data in the POST request.

**Expected behaviour**
I'd expect this to return an HTTP error code (e.g. 422) and a JSON representation of what was wrong.

What actually happens is I get an HTTP 201 code, and a log that indicates it failed.

**System:**
 - OS: [e.g. Ubuntu 19.10]
 - Python version [e.g. 3.8]
 - Version [e.g. 0.1.0]

**Additional context**
The problem is that argument processing is wrapped into the function that's called in the thread.  This means that the exception raised by webargs/marshmallow (which would ordinarily get handled by Flask and raise a 422 error, and can be improved with the webargs example code to return a JSON representation of what was wrong with the data) gets swallowed by our thread exception handling mechanism.

I have tried adding a couple of lines of code to propagate the error back to the ActionView, which restores the expected behaviour, but it's possible it introduces other bugs in situations I've not considered (e.g. where an error occurs in the action function at the start).

Possible solutions:
* Explicitly check for, and handle, marshmallow exceptions in ActionThread
* Move argument processing out of the action function (this would require getting rid of the decorator-style ``use_args`` and reverting to something a bit more mundane

I'm happy to send a pull request with a fix, but thought it was worth posting here in case there is a discussion worth having.

**Comment by jtc42** [comment]
Oh good catch! Honestly amazed this didn't screw up earlier...

More than happy to accept a PR, otherwise I'll take a look when I get chance.

**Comment by rwb27** [comment]
We went through a bunch of iterations of this sort of thing, I'm not surprised the final one wasn't perfect!
