### ISSUE TITLE
Greenlets, threading, and locks

### ISSUE THREAD

**Issue by rwb27** [labthings/python-labthings#32]
I had a wierd issue with my serial instrument today, which turned out to be due to the way LabThings was using greenlets.  I thought it would be worth writing it up here, even though we fixed it, because this is the sort of thing that rears its ugly head in the future when you have forgotten about it.  Here follows a cautionary tale.

LabThings uses greenlets as an alternative to native threads. By "native threads" I specifically mean what you'd get if you used the ``threading`` module from the standard library.  Greenlets have a lot of performance advantages, and it's temptingly easy to switch from threads to greenlets by 
"monkey-patching" the standard library, so that anything in the ``threading`` library actually gives you something from the ``gevent`` library instead.

The problem was, when I hit this issue, that the ``threading`` library wasn't being monkey-patched, so my code (which was written before LabThings existed) was using unmodified ``threading.RLock`` objects to make sure my I/O worked correctly.  When this ran in the LabThings server, it made concurrent calls to a function (let's call it ``query``) which contained a ``time.sleep`` call in between two bits of I/O.  The lock should have protected it, but it would only have protected it from another ``threading.Thread``.  Because the ``time`` module **had** been monkey-patched, ``gevent`` context-switched during the call to ``sleep`` and broke my I/O.  This was confusing to debug!

**Comment by rwb27** [comment]
If we want to let old code keep using standard threads (has the advantage of not inducing unexpected effects in said code) we can't monkey-patch the ``threading`` library completely.  However, then ``threading.RLock`` objects won't protect us properly.

I think the solution is to monkey-patch ``RLock`` but not ``Thread``.  The monkey-patched ``RLock`` relies on ``gevent.getcurrent()`` to identify the greenlet that we are currently in - you can only acquire the ``RLock`` if it is either free, or already acquired by your greenlet.  *I believe that if you are in a different thread, ``gevent.getcurrent()`` will return a different value.*  This means that the monkey-patched ``RLock`` still protects against race conditions between ``threading.Thread``s as well as also being safe with respect to greenlets.

**Comment by rwb27** [comment]
My assertion about ``getcurrent()`` returning a different value if you're in a thread can be tested experimentally, but it would be very reassuring to check that this is the intended behaviour, and not just a useful side-effect.  My demonstration:
```
>>> import gevent
>>> import threading
>>> def idg():
...     print(gevent.getcurrent())
... 
>>> t = threading.Thread(target=idg)
>>> t.start()
<greenlet.greenlet object at 0x7635db30>
>>> idg()
<greenlet.greenlet object at 0x7648f818>
```

**Comment by jtc42** [comment]
This does actually seem to be the intended behaviour:
https://stackoverflow.com/questions/17005661/why-does-greenlet-getcurrent-work-if-i-havent-started-a-greenlet

https://github.com/python-greenlet/greenlet/blob/master/greenlet.c#L1367
and
https://github.com/python-greenlet/greenlet/blob/master/greenlet.c#L125

getcurrent(), once you've followed it back to the C code for `greenlet` falls back to PyThreadState_GET(), which returns the current thread state 
https://docs.python.org/3.7/c-api/init.html#c.PyThreadState_Get

This should then be safe to use.

Annoyingly, until gevent 1.5 is released, I'll have to reimplement the 1.5 Gevent RLock in LabThings as 1.4 doesn't have a lock timeout, which we use quite a lot. Once 1.5 is out, I'll switch to using normal Gevent RLocks.

One final note, I think for simplicity I'll add a monkey submodule to LabThings that performs the subset of suggested Gevent patches (i.e. everything except for threading).

**Comment by rwb27** [comment]
That makes sense - I just looked at the source on github which was presumably v1.5.

**Comment by jtc42** [comment]
> That makes sense - I just looked at the source on github which was presumably v1.5.

Yeah I got hit by that mistake too. I’ll set up release notifications so we can move away from reimplementing asap.
