### ISSUE TITLE
Add a proper readme

### ISSUE THREAD

**Issue by jtc42** [labthings/python-labthings#4]

**Comment by jtc42** [comment]
Good first example (needs simplifying a bit first)
https://github.com/labthings/python-labthings/blob/master/examples/builder.py

**Comment by ChasNelson1990** [comment]
Erm.... did you post this to the right issue?

**Comment by jtc42** [comment]
Sorry yeah that's a note for me, should have been clear. I want a super simple example in the readme.

**Comment by jtc42** [comment]
Now included. Closing
