### ISSUE TITLE
No tags/releases on github for 0.4.0

### ISSUE THREAD

**Issue by rwb27** [labthings/python-labthings#50]
``pip install labthings==0.4.0`` works, so clearly there is a version 0.4.0.  However, I don't know what commit that corresponds to - on my development machine, that's quite annoying...

Am I missing something in the branch/tag workflow?

**Comment by jtc42** [comment]
Yeah looking now I've been really bad for remembering to tag releases. What I'll do this week is set up tags to actually do the PyPI releases, so the two are always in sync.

**Comment by jtc42** [comment]
Not that it's particularly useful any more, but the 0.4.0 release has now been retrospectively added.
