### ISSUE TITLE
Default log level for tasks

### ISSUE THREAD

**Issue by rwb27** [labthings/python-labthings#52]
When I knocked up the task logging code, I set the log level to INFO deliberately - my intention was that this would function as a nice way to get a status display out of a task, and so you definitely do want to get INFO messages out rather than just WARNING ones.  I see the default level in the log handler is now WARNING, which means INFO messages are ignored (regardless of the top-level setting).

I think it would be reasonable to hard-code it at INFO, if not beautiful.  If we're not going to do that, I think we need a way to specify the log leve, either when the task is created (e.g. by ``taskify``) or in a configuration parameter somewhere.

**Comment by jtc42** [comment]
Yeah that all makes sense. I'll fix this asap as it should only take a minute.

**Comment by rwb27** [comment]
Will take seconds to send a PR if you want it, I just changed the default.

**Comment by jtc42** [comment]
It's cool I've just done it. Adding a way to override it now.

**Comment by rwb27** [comment]
I think this is done, right?  Unless you want to keep the issue open until there's an option to override, I think it can be closed - maybe I'll close it and you can re-open if you want to hold it for an override?

You updated the loglevel in 6ae5f935ed989483a9b70678d01eadc5ae3a3b4b
